# Generated by Django 4.0.4 on 2023-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOfBOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1500)),
                ('photo', models.ImageField(upload_to='MessageBOD/%name')),
                ('video', models.FileField(blank=True, upload_to='MessageBOD/%name')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('video_file', models.FileField(blank=True, upload_to='video/programs/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('video_file', models.FileField(blank=True, upload_to='video/programs/%y/%m/%d')),
            ],
        ),
    ]
