# Generated by Django 4.0.4 on 2023-06-09 10:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_contactusdb_joinacharya_alter_messageofbod_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageofbod',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programs',
            name='images',
            field=models.ImageField(blank=True, upload_to='Programs/images/'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
