# Generated by Django 4.0.4 on 2023-07-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_messageofbod_message_alter_notices_description_and_more'),
        ('homepage', '0005_auto_20230609_1231'),
    ]

    operations = [
    ]
