# Generated by Django 4.0.4 on 2023-07-31 05:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_merge_20230729_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageofbod',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
